@startuml network

' This doesn't work for plantuml.com
' Uncomment for local server and delete all the styling below
!include style.puml

node Server {
    node "VM" {
        database "mongodb"
        node "nodejs"
    }
}

node "iPad"

node Router

cloud Internet

Internet -down- Server : eth2
iPad -right- Router : WiFi
Router -right- Server : eth1
mongodb -down- nodejs: mongoDB native


@enduml