@startuml sm
' Uncomment to enable black and white mode
' !$black_and_white = 1

' Uncomment to force all arrows vertical and horizontal
skinparam linetype ortho

' Uncomment to force all arrows diagonal, vertical and horizontal
' skinparam linetype polyline

' Uncomment to force left to right direction
' left to right direction

' Include standard AMRC stylesheet
!include style.puml

state Login
state Overview
state Menu
state Settings
state "Building Sidebar" as bs

[*] --> Login
Login --> Overview
Overview --> bs
bs --> Overview

Overview --> Menu
bs --> Menu


Menu --> Settings
Settings --> Menu
Menu --> Login


@enduml